-- ESEJUR - EP01 Acceso y descubrimiento
-- PostgreSQL 15+
-- Alcance: tablas, columnas, llaves primarias, llaves foraneas y unicidad.
-- No contiene funciones, triggers, procedimientos, vistas ni indices adicionales.

BEGIN;

CREATE SCHEMA IF NOT EXISTS esejur;
SET search_path TO esejur, public;

-- -----------------------------------------------------------------------------
-- Cuenta, acceso y perfil
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS rol (
    rol_id         bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo         varchar(50) NOT NULL,
    nombre         varchar(100) NOT NULL,
    descripcion    text,
    activo         boolean NOT NULL DEFAULT true,
    creado_en      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_rol PRIMARY KEY (rol_id),
    CONSTRAINT uq_rol_codigo UNIQUE (codigo)
);

COMMENT ON TABLE esejur.rol IS
'Catalogo de roles disponibles en el sistema.';
COMMENT ON COLUMN esejur.rol.rol_id IS 'Identificador interno unico del rol.';
COMMENT ON COLUMN esejur.rol.codigo IS 'Codigo unico utilizado para identificar el rol dentro del sistema.';
COMMENT ON COLUMN esejur.rol.nombre IS 'Nombre del rol mostrado en la administracion.';
COMMENT ON COLUMN esejur.rol.descripcion IS 'Explicacion funcional de los permisos generales del rol.';
COMMENT ON COLUMN esejur.rol.activo IS 'Indica si el rol puede seguir asignandose a cuentas de usuario.';
COMMENT ON COLUMN esejur.rol.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.rol.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS persona (
    persona_id                       bigint GENERATED BY DEFAULT AS IDENTITY,
    nombres                          varchar(120) NOT NULL,
    apellido_paterno                 varchar(80) NOT NULL,
    apellido_materno                 varchar(80),
    telefono                         varchar(30),
    documento_identidad              varchar(30),
    foto_url                         text,
    cargo_profesional                varchar(180),
    biografia_profesional            text,
    datos_certificado_confirmados_en timestamptz,
    activo                           boolean NOT NULL DEFAULT true,
    creado_en                        timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en                    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_persona PRIMARY KEY (persona_id),
    CONSTRAINT uq_persona_documento_identidad UNIQUE (documento_identidad)
);

COMMENT ON TABLE esejur.persona IS
'Almacena una sola identidad para alumnos, administradores y docentes, tengan o no cuenta de acceso.';
COMMENT ON COLUMN esejur.persona.persona_id IS 'Identificador interno unico de la persona.';
COMMENT ON COLUMN esejur.persona.nombres IS 'Nombres de la persona.';
COMMENT ON COLUMN esejur.persona.apellido_paterno IS 'Apellido paterno de la persona.';
COMMENT ON COLUMN esejur.persona.apellido_materno IS 'Apellido materno opcional de la persona.';
COMMENT ON COLUMN esejur.persona.telefono IS 'Numero telefonico opcional de contacto.';
COMMENT ON COLUMN esejur.persona.documento_identidad IS 'Documento de identidad opcional; no se imprime en el certificado.';
COMMENT ON COLUMN esejur.persona.foto_url IS 'Ubicacion de la fotografia opcional de la persona.';
COMMENT ON COLUMN esejur.persona.cargo_profesional IS 'Cargo o especialidad profesional mostrada cuando participa como docente.';
COMMENT ON COLUMN esejur.persona.biografia_profesional IS 'Resena profesional publica utilizada cuando participa como docente.';
COMMENT ON COLUMN esejur.persona.datos_certificado_confirmados_en IS 'Fecha y hora de confirmacion de nombres y apellidos para certificacion.';
COMMENT ON COLUMN esejur.persona.activo IS 'Indica si la persona puede seguir utilizandose en nuevos procesos.';
COMMENT ON COLUMN esejur.persona.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.persona.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS usuario (
    usuario_id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    persona_id                  bigint NOT NULL,
    correo                      varchar(254) NOT NULL,
    origen_registro             varchar(20) NOT NULL,
    estado                      varchar(30) NOT NULL,
    contrasena_hash             text,
    google_subject              varchar(255),
    requiere_cambio_contrasena  boolean NOT NULL DEFAULT false,
    correo_verificado_en        timestamptz,
    creado_por_usuario_id       bigint,
    deshabilitado_en            timestamptz,
    ultimo_acceso_en            timestamptz,
    creado_en                   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en               timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_persona UNIQUE (persona_id),
    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT uq_usuario_google_subject UNIQUE (google_subject),
    CONSTRAINT fk_usuario_persona
        FOREIGN KEY (persona_id) REFERENCES persona(persona_id),
    CONSTRAINT fk_usuario_creado_por
        FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);

COMMENT ON TABLE esejur.usuario IS
'Almacena las cuentas de acceso de alumnos y administradores vinculadas con una persona.';
COMMENT ON COLUMN esejur.usuario.usuario_id IS 'Identificador interno unico de la cuenta de usuario.';
COMMENT ON COLUMN esejur.usuario.persona_id IS 'Persona propietaria de la cuenta; una persona puede tener como maximo una cuenta.';
COMMENT ON COLUMN esejur.usuario.correo IS 'Correo usado como identificador unico de acceso.';
COMMENT ON COLUMN esejur.usuario.origen_registro IS 'Medio por el cual se creo la cuenta: formulario, Google o administracion.';
COMMENT ON COLUMN esejur.usuario.estado IS 'Situacion actual de la cuenta respecto a verificacion y acceso.';
COMMENT ON COLUMN esejur.usuario.contrasena_hash IS 'Hash de la contrasena; nunca contiene la contrasena en texto plano.';
COMMENT ON COLUMN esejur.usuario.google_subject IS 'Identificador unico entregado por Google para la cuenta vinculada.';
COMMENT ON COLUMN esejur.usuario.requiere_cambio_contrasena IS 'Indica si debe cambiar la contrasena temporal al ingresar.';
COMMENT ON COLUMN esejur.usuario.correo_verificado_en IS 'Fecha y hora en que el correo quedo verificado.';
COMMENT ON COLUMN esejur.usuario.creado_por_usuario_id IS 'Administrador que creo la cuenta, cuando el registro fue administrativo.';
COMMENT ON COLUMN esejur.usuario.deshabilitado_en IS 'Fecha y hora en que se deshabilito la cuenta.';
COMMENT ON COLUMN esejur.usuario.ultimo_acceso_en IS 'Fecha y hora del ultimo acceso exitoso.';
COMMENT ON COLUMN esejur.usuario.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.usuario.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS usuario_rol (
    usuario_id  bigint NOT NULL,
    rol_id      bigint NOT NULL,
    asignado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario_rol PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id),
    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (rol_id) REFERENCES rol(rol_id)
);

COMMENT ON TABLE esejur.usuario_rol IS
'Asigna uno o varios roles del sistema a cada cuenta de usuario.';
COMMENT ON COLUMN esejur.usuario_rol.usuario_id IS 'Usuario que recibe el rol.';
COMMENT ON COLUMN esejur.usuario_rol.rol_id IS 'Rol asignado al usuario.';
COMMENT ON COLUMN esejur.usuario_rol.asignado_en IS 'Fecha y hora en que se realizo la asignacion.';

CREATE TABLE IF NOT EXISTS codigo_verificacion_correo (
    codigo_verificacion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id              bigint NOT NULL,
    codigo_hash             text NOT NULL,
    estado                  varchar(15) NOT NULL DEFAULT 'VIGENTE',
    estado_envio            varchar(15) NOT NULL DEFAULT 'PENDIENTE',
    solicitado_en           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utilizado_en            timestamptz,
    invalidado_en           timestamptz,
    modificado_en           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_codigo_verificacion_correo PRIMARY KEY (codigo_verificacion_id),
    CONSTRAINT uq_codigo_verificacion_hash UNIQUE (codigo_hash),
    CONSTRAINT fk_codigo_verificacion_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id)
);

COMMENT ON TABLE esejur.codigo_verificacion_correo IS
'Almacena los codigos emitidos para verificar el correo de una cuenta.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.codigo_verificacion_id IS 'Identificador interno unico de la emision del codigo.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.usuario_id IS 'Usuario cuyo correo debe ser verificado.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.codigo_hash IS 'Hash del codigo de verificacion; no conserva el codigo visible.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.estado IS 'Situacion del codigo: vigente, utilizado o invalidado.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.estado_envio IS 'Resultado del intento de entrega del correo.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.solicitado_en IS 'Fecha y hora en que se genero el codigo.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.utilizado_en IS 'Fecha y hora en que el codigo fue validado correctamente.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.invalidado_en IS 'Fecha y hora en que el codigo perdio validez.';
COMMENT ON COLUMN esejur.codigo_verificacion_correo.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS token_recuperacion_acceso (
    token_recuperacion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id            bigint NOT NULL,
    token_hash            text NOT NULL,
    estado                varchar(15) NOT NULL DEFAULT 'VIGENTE',
    estado_envio          varchar(15) NOT NULL DEFAULT 'PENDIENTE',
    solicitado_en         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_en             timestamptz NOT NULL,
    utilizado_en          timestamptz,
    invalidado_en         timestamptz,
    modificado_en         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_token_recuperacion_acceso PRIMARY KEY (token_recuperacion_id),
    CONSTRAINT uq_token_recuperacion_hash UNIQUE (token_hash),
    CONSTRAINT fk_token_recuperacion_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id)
);

COMMENT ON TABLE esejur.token_recuperacion_acceso IS
'Almacena los enlaces temporales emitidos para recuperar el acceso a una cuenta.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.token_recuperacion_id IS 'Identificador interno unico de la solicitud de recuperacion.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.usuario_id IS 'Usuario que solicito recuperar su acceso.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.token_hash IS 'Hash del token; no conserva el valor enviado al usuario.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.estado IS 'Situacion del token: vigente, utilizado o invalidado.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.estado_envio IS 'Resultado del intento de entrega del correo de recuperacion.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.solicitado_en IS 'Fecha y hora de solicitud del enlace.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.expira_en IS 'Fecha y hora limite para utilizar el enlace.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.utilizado_en IS 'Fecha y hora en que el enlace fue utilizado.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.invalidado_en IS 'Fecha y hora en que el enlace fue invalidado.';
COMMENT ON COLUMN esejur.token_recuperacion_acceso.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

-- -----------------------------------------------------------------------------
-- Maestros del catalogo
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tipo_curso (
    tipo_curso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo        varchar(50) NOT NULL,
    nombre        varchar(120) NOT NULL,
    activo        boolean NOT NULL DEFAULT true,
    orden         integer NOT NULL DEFAULT 0,
    creado_en     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tipo_curso PRIMARY KEY (tipo_curso_id),
    CONSTRAINT uq_tipo_curso_codigo UNIQUE (codigo)
);

COMMENT ON TABLE esejur.tipo_curso IS
'Catalogo de tipos comerciales de curso usados para clasificar y filtrar la oferta.';
COMMENT ON COLUMN esejur.tipo_curso.tipo_curso_id IS 'Identificador interno unico del tipo de curso.';
COMMENT ON COLUMN esejur.tipo_curso.codigo IS 'Codigo estable utilizado por el sistema.';
COMMENT ON COLUMN esejur.tipo_curso.nombre IS 'Nombre visible del tipo de curso.';
COMMENT ON COLUMN esejur.tipo_curso.activo IS 'Indica si el tipo puede seguir utilizandose.';
COMMENT ON COLUMN esejur.tipo_curso.orden IS 'Posicion de presentacion en selectores y filtros.';
COMMENT ON COLUMN esejur.tipo_curso.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.tipo_curso.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS categoria_tematica (
    categoria_tematica_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo                varchar(50) NOT NULL,
    nombre                varchar(120) NOT NULL,
    activo                boolean NOT NULL DEFAULT true,
    orden                 integer NOT NULL DEFAULT 0,
    creado_en             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_categoria_tematica PRIMARY KEY (categoria_tematica_id),
    CONSTRAINT uq_categoria_tematica_codigo UNIQUE (codigo)
);

COMMENT ON TABLE esejur.categoria_tematica IS
'Catalogo de areas juridicas utilizadas para clasificar y filtrar cursos.';
COMMENT ON COLUMN esejur.categoria_tematica.categoria_tematica_id IS 'Identificador interno unico de la categoria tematica.';
COMMENT ON COLUMN esejur.categoria_tematica.codigo IS 'Codigo estable utilizado por el sistema.';
COMMENT ON COLUMN esejur.categoria_tematica.nombre IS 'Nombre visible del area juridica.';
COMMENT ON COLUMN esejur.categoria_tematica.activo IS 'Indica si la categoria puede seguir utilizandose.';
COMMENT ON COLUMN esejur.categoria_tematica.orden IS 'Posicion de presentacion en selectores y filtros.';
COMMENT ON COLUMN esejur.categoria_tematica.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.categoria_tematica.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS entidad_certificadora (
    entidad_certificadora_id bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre                   varchar(200) NOT NULL,
    logo_url                 text,
    activo                   boolean NOT NULL DEFAULT true,
    creado_en                timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en            timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_entidad_certificadora PRIMARY KEY (entidad_certificadora_id),
    CONSTRAINT uq_entidad_certificadora_nombre UNIQUE (nombre)
);

COMMENT ON TABLE esejur.entidad_certificadora IS
'Catalogo de instituciones que pueden refrendar la certificacion de un curso.';
COMMENT ON COLUMN esejur.entidad_certificadora.entidad_certificadora_id IS 'Identificador interno unico de la entidad certificadora.';
COMMENT ON COLUMN esejur.entidad_certificadora.nombre IS 'Nombre oficial visible de la entidad.';
COMMENT ON COLUMN esejur.entidad_certificadora.logo_url IS 'Ubicacion del logotipo de la entidad, cuando exista.';
COMMENT ON COLUMN esejur.entidad_certificadora.activo IS 'Indica si la entidad puede asignarse a nuevos cursos.';
COMMENT ON COLUMN esejur.entidad_certificadora.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.entidad_certificadora.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';



-- -----------------------------------------------------------------------------
-- Curso, temario y vista previa
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS curso (
    curso_id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    curso_origen_id          bigint,
    url_amigable             varchar(180) NOT NULL,
    titulo                   varchar(220) NOT NULL,
    descripcion              text,
    imagen_portada_url       text,
    tipo_curso_id            bigint,
    categoria_tematica_id    bigint,
    entidad_certificadora_id bigint,
    modalidad                varchar(15),
    tipo_venta               varchar(10),
    estado                   varchar(15) NOT NULL DEFAULT 'BORRADOR',
    destacado                boolean NOT NULL DEFAULT false,
    precio_regular           numeric(10,2) NOT NULL DEFAULT 0,
    precio_promocional       numeric(10,2),
    promocion_inicio_en      timestamptz,
    promocion_fin_en         timestamptz,
    fecha_inicio             date,
    fecha_fin                date,
    fecha_cierre_matricula   date,
    cupo_maximo              integer,
    horas_academicas         numeric(8,2),
    beneficios               text[] NOT NULL DEFAULT ARRAY[]::text[],
    creado_por_usuario_id    bigint,
    publicado_en             timestamptz,
    cerrado_en               timestamptz,
    cancelado_en             timestamptz,
    creado_en                timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en            timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_curso PRIMARY KEY (curso_id),
    CONSTRAINT uq_curso_url_amigable UNIQUE (url_amigable),
    CONSTRAINT fk_curso_origen
        FOREIGN KEY (curso_origen_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_curso_tipo
        FOREIGN KEY (tipo_curso_id) REFERENCES tipo_curso(tipo_curso_id),
    CONSTRAINT fk_curso_categoria
        FOREIGN KEY (categoria_tematica_id) REFERENCES categoria_tematica(categoria_tematica_id),
    CONSTRAINT fk_curso_entidad_certificadora
        FOREIGN KEY (entidad_certificadora_id)
        REFERENCES entidad_certificadora(entidad_certificadora_id),
    CONSTRAINT fk_curso_creado_por
        FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);

COMMENT ON TABLE esejur.curso IS
'Almacena la ficha comercial y academica de cada curso ofrecido por la Escuela.';
COMMENT ON COLUMN esejur.curso.curso_id IS 'Identificador interno unico del curso.';
COMMENT ON COLUMN esejur.curso.curso_origen_id IS 'Curso usado como origen cuando se duplica contenido para una nueva oferta.';
COMMENT ON COLUMN esejur.curso.url_amigable IS 'Texto unico utilizado en la direccion publica de la ficha.';
COMMENT ON COLUMN esejur.curso.titulo IS 'Nombre comercial visible del curso.';
COMMENT ON COLUMN esejur.curso.descripcion IS 'Descripcion general presentada en catalogo y ficha.';
COMMENT ON COLUMN esejur.curso.imagen_portada_url IS 'Ubicacion de la imagen principal del curso.';
COMMENT ON COLUMN esejur.curso.tipo_curso_id IS 'Tipo comercial asignado al curso.';
COMMENT ON COLUMN esejur.curso.categoria_tematica_id IS 'Area juridica principal asignada al curso.';
COMMENT ON COLUMN esejur.curso.entidad_certificadora_id IS 'Entidad que refrenda la certificacion del curso.';
COMMENT ON COLUMN esejur.curso.modalidad IS 'Forma de desarrollo del curso: virtual, en vivo o hibrido.';
COMMENT ON COLUMN esejur.curso.tipo_venta IS 'Indica si el acceso al curso es gratuito o pagado.';
COMMENT ON COLUMN esejur.curso.estado IS 'Situacion actual de publicacion y desarrollo del curso.';
COMMENT ON COLUMN esejur.curso.destacado IS 'Indica si el curso recibe posicion preferente en el catalogo.';
COMMENT ON COLUMN esejur.curso.precio_regular IS 'Precio normal del curso en soles.';
COMMENT ON COLUMN esejur.curso.precio_promocional IS 'Precio promocional opcional en soles.';
COMMENT ON COLUMN esejur.curso.promocion_inicio_en IS 'Fecha y hora desde la que aplica el precio promocional.';
COMMENT ON COLUMN esejur.curso.promocion_fin_en IS 'Fecha y hora hasta la que aplica el precio promocional.';
COMMENT ON COLUMN esejur.curso.fecha_inicio IS 'Fecha de inicio para cursos en vivo o hibridos.';
COMMENT ON COLUMN esejur.curso.fecha_fin IS 'Fecha de finalizacion para cursos en vivo o hibridos; permanece vacia en virtuales.';
COMMENT ON COLUMN esejur.curso.fecha_cierre_matricula IS 'Ultimo dia permitido para matricularse, cuando corresponda.';
COMMENT ON COLUMN esejur.curso.cupo_maximo IS 'Cantidad maxima de matriculas activas permitidas, si existe limite.';
COMMENT ON COLUMN esejur.curso.horas_academicas IS 'Duracion academica total comunicada en la ficha.';
COMMENT ON COLUMN esejur.curso.beneficios IS 'Lista ordenada de beneficios propios del curso.';
COMMENT ON COLUMN esejur.curso.creado_por_usuario_id IS 'Administrador que creo el curso.';
COMMENT ON COLUMN esejur.curso.publicado_en IS 'Fecha y hora en que el curso se hizo visible.';
COMMENT ON COLUMN esejur.curso.cerrado_en IS 'Fecha y hora en que el curso fue cerrado.';
COMMENT ON COLUMN esejur.curso.cancelado_en IS 'Fecha y hora en que el curso fue cancelado.';
COMMENT ON COLUMN esejur.curso.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.curso.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS curso_docente (
    curso_id   bigint NOT NULL,
    persona_id bigint NOT NULL,
    orden      integer NOT NULL,
    creado_en  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_curso_docente PRIMARY KEY (curso_id, persona_id),
    CONSTRAINT uq_curso_docente_orden UNIQUE (curso_id, orden),
    CONSTRAINT fk_curso_docente_curso
        FOREIGN KEY (curso_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_curso_docente_persona
        FOREIGN KEY (persona_id) REFERENCES persona(persona_id)
);

COMMENT ON TABLE esejur.curso_docente IS
'Relaciona una persona con el curso en el que participa como docente y define su orden de presentacion.';
COMMENT ON COLUMN esejur.curso_docente.curso_id IS 'Curso al que pertenece la asignacion docente.';
COMMENT ON COLUMN esejur.curso_docente.persona_id IS 'Persona que aparece como docente del curso.';
COMMENT ON COLUMN esejur.curso_docente.orden IS 'Posicion del docente dentro de la ficha del curso.';
COMMENT ON COLUMN esejur.curso_docente.creado_en IS 'Fecha y hora en que se creo la asignacion.';

CREATE TABLE IF NOT EXISTS modulo (
    modulo_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    curso_id      bigint NOT NULL,
    titulo        varchar(220) NOT NULL,
    descripcion   text,
    orden         integer NOT NULL,
    activo        boolean NOT NULL DEFAULT true,
    creado_en     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_modulo PRIMARY KEY (modulo_id),
    CONSTRAINT uq_modulo_curso_orden UNIQUE (curso_id, orden),
    CONSTRAINT fk_modulo_curso
        FOREIGN KEY (curso_id) REFERENCES curso(curso_id)
);

COMMENT ON TABLE esejur.modulo IS
'Almacena los modulos ordenados que conforman el temario de un curso.';
COMMENT ON COLUMN esejur.modulo.modulo_id IS 'Identificador interno unico del modulo.';
COMMENT ON COLUMN esejur.modulo.curso_id IS 'Curso al que pertenece el modulo.';
COMMENT ON COLUMN esejur.modulo.titulo IS 'Titulo visible del modulo.';
COMMENT ON COLUMN esejur.modulo.descripcion IS 'Descripcion opcional del contenido del modulo.';
COMMENT ON COLUMN esejur.modulo.orden IS 'Posicion del modulo dentro del curso.';
COMMENT ON COLUMN esejur.modulo.activo IS 'Indica si el modulo permanece disponible en el temario.';
COMMENT ON COLUMN esejur.modulo.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.modulo.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS leccion (
    leccion_id         bigint GENERATED BY DEFAULT AS IDENTITY,
    modulo_id          bigint NOT NULL,
    titulo             varchar(220) NOT NULL,
    descripcion        text,
    orden              integer NOT NULL,
    tipo               varchar(10) NOT NULL,
    estado             varchar(15) NOT NULL,
    es_obligatoria     boolean NOT NULL DEFAULT true,
    es_vista_previa    boolean NOT NULL DEFAULT false,
    fecha_hora_inicio  timestamptz,
    fecha_hora_fin     timestamptz,
    enlace_reunion     text,
    motivo_cancelacion text,
    activo             boolean NOT NULL DEFAULT true,
    creado_en          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_leccion PRIMARY KEY (leccion_id),
    CONSTRAINT uq_leccion_modulo_orden UNIQUE (modulo_id, orden),
    CONSTRAINT fk_leccion_modulo
        FOREIGN KEY (modulo_id) REFERENCES modulo(modulo_id)
);

COMMENT ON TABLE esejur.leccion IS
'Almacena las lecciones ordenadas de cada modulo, incluidas las vistas previas.';
COMMENT ON COLUMN esejur.leccion.leccion_id IS 'Identificador interno unico de la leccion.';
COMMENT ON COLUMN esejur.leccion.modulo_id IS 'Modulo al que pertenece la leccion.';
COMMENT ON COLUMN esejur.leccion.titulo IS 'Titulo visible de la leccion.';
COMMENT ON COLUMN esejur.leccion.descripcion IS 'Descripcion opcional del contenido de la leccion.';
COMMENT ON COLUMN esejur.leccion.orden IS 'Posicion de la leccion dentro del modulo.';
COMMENT ON COLUMN esejur.leccion.tipo IS 'Tipo de desarrollo de la leccion, grabada o en vivo.';
COMMENT ON COLUMN esejur.leccion.estado IS 'Situacion actual de disponibilidad o programacion de la leccion.';
COMMENT ON COLUMN esejur.leccion.es_obligatoria IS 'Indica si completar la leccion forma parte de los requisitos del curso.';
COMMENT ON COLUMN esejur.leccion.es_vista_previa IS 'Indica si la leccion puede consultarse antes de matricularse.';
COMMENT ON COLUMN esejur.leccion.fecha_hora_inicio IS 'Fecha y hora de inicio de una leccion en vivo.';
COMMENT ON COLUMN esejur.leccion.fecha_hora_fin IS 'Fecha y hora de finalizacion de una leccion en vivo.';
COMMENT ON COLUMN esejur.leccion.enlace_reunion IS 'Enlace privado de acceso a la sesion en vivo.';
COMMENT ON COLUMN esejur.leccion.motivo_cancelacion IS 'Explicacion de la cancelacion de una sesion, cuando corresponda.';
COMMENT ON COLUMN esejur.leccion.activo IS 'Indica si la leccion permanece disponible dentro del modulo.';
COMMENT ON COLUMN esejur.leccion.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.leccion.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS recurso (
    recurso_id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo                          varchar(15) NOT NULL,
    origen                        varchar(20) NOT NULL,
    referencia                    text NOT NULL,
    nombre_archivo                varchar(255),
    tipo_mime                     varchar(150),
    tamano_bytes                  bigint,
    duracion_segundos             integer,
    duracion_detectada            boolean NOT NULL DEFAULT false,
    youtube_no_listado_confirmado boolean,
    creado_por_usuario_id         bigint,
    activo                        boolean NOT NULL DEFAULT true,
    creado_en                     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en                 timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_recurso PRIMARY KEY (recurso_id),
    CONSTRAINT uq_recurso_referencia UNIQUE (referencia),
    CONSTRAINT fk_recurso_creado_por
        FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);

COMMENT ON TABLE esejur.recurso IS
'Almacena archivos, videos o enlaces reutilizables como materiales de una leccion.';
COMMENT ON COLUMN esejur.recurso.recurso_id IS 'Identificador interno unico del recurso.';
COMMENT ON COLUMN esejur.recurso.tipo IS 'Formato funcional del recurso, como video, PDF o enlace.';
COMMENT ON COLUMN esejur.recurso.origen IS 'Procedencia del recurso: archivo local, YouTube o enlace externo.';
COMMENT ON COLUMN esejur.recurso.referencia IS 'Clave de almacenamiento o direccion que permite localizar el recurso.';
COMMENT ON COLUMN esejur.recurso.nombre_archivo IS 'Nombre original o visible del archivo.';
COMMENT ON COLUMN esejur.recurso.tipo_mime IS 'Tipo de contenido tecnico del archivo.';
COMMENT ON COLUMN esejur.recurso.tamano_bytes IS 'Tamano del archivo expresado en bytes.';
COMMENT ON COLUMN esejur.recurso.duracion_segundos IS 'Duracion total del audio o video expresada en segundos.';
COMMENT ON COLUMN esejur.recurso.duracion_detectada IS 'Indica si la duracion fue obtenida automaticamente al subir el archivo.';
COMMENT ON COLUMN esejur.recurso.youtube_no_listado_confirmado IS 'Confirma que un video de YouTube fue configurado como no listado.';
COMMENT ON COLUMN esejur.recurso.creado_por_usuario_id IS 'Administrador que registro o subio el recurso.';
COMMENT ON COLUMN esejur.recurso.activo IS 'Indica si el recurso puede seguir utilizandose.';
COMMENT ON COLUMN esejur.recurso.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.recurso.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

CREATE TABLE IF NOT EXISTS material_leccion (
    material_leccion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    leccion_id          bigint NOT NULL,
    recurso_id          bigint NOT NULL,
    titulo              varchar(220) NOT NULL,
    orden               integer NOT NULL,
    permite_descarga    boolean NOT NULL DEFAULT false,
    activo              boolean NOT NULL DEFAULT true,
    creado_en           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_material_leccion PRIMARY KEY (material_leccion_id),
    CONSTRAINT uq_material_leccion_orden UNIQUE (leccion_id, orden),
    CONSTRAINT fk_material_leccion_leccion
        FOREIGN KEY (leccion_id) REFERENCES leccion(leccion_id),
    CONSTRAINT fk_material_leccion_recurso
        FOREIGN KEY (recurso_id) REFERENCES recurso(recurso_id)
);

COMMENT ON TABLE esejur.material_leccion IS
'Define el uso, titulo y posicion de un recurso dentro de una leccion.';
COMMENT ON COLUMN esejur.material_leccion.material_leccion_id IS 'Identificador interno unico del material colocado en la leccion.';
COMMENT ON COLUMN esejur.material_leccion.leccion_id IS 'Leccion en la que se utiliza el recurso.';
COMMENT ON COLUMN esejur.material_leccion.recurso_id IS 'Recurso utilizado como material.';
COMMENT ON COLUMN esejur.material_leccion.titulo IS 'Titulo con el que el material se muestra en la leccion.';
COMMENT ON COLUMN esejur.material_leccion.orden IS 'Posicion del material dentro de la leccion.';
COMMENT ON COLUMN esejur.material_leccion.permite_descarga IS 'Indica si el alumno puede descargar el material.';
COMMENT ON COLUMN esejur.material_leccion.activo IS 'Indica si el material permanece visible en la leccion.';
COMMENT ON COLUMN esejur.material_leccion.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.material_leccion.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

-- Esta tabla aporta el dato de cupos ocupados que muestran HU-006 y HU-007.
-- Los pagos y el flujo completo de matricula corresponden a EP02.
CREATE TABLE IF NOT EXISTS matricula (
    matricula_id          bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id            bigint NOT NULL,
    curso_id              bigint NOT NULL,
    estado                varchar(12) NOT NULL,
    forma_ingreso         varchar(25) NOT NULL,
    fecha_matricula       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_activacion      timestamptz,
    fecha_vencimiento     timestamptz,
    motivo_cancelacion    text,
    creado_por_usuario_id bigint,
    creado_en             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_matricula PRIMARY KEY (matricula_id),
    CONSTRAINT uq_matricula_usuario_curso UNIQUE (usuario_id, curso_id),
    CONSTRAINT fk_matricula_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id),
    CONSTRAINT fk_matricula_curso
        FOREIGN KEY (curso_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_matricula_creado_por
        FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);

COMMENT ON TABLE esejur.matricula IS
'Relaciona un usuario con un curso y conserva el estado necesario para controlar acceso y cupos.';
COMMENT ON COLUMN esejur.matricula.matricula_id IS 'Identificador interno unico de la matricula.';
COMMENT ON COLUMN esejur.matricula.usuario_id IS 'Usuario matriculado en el curso.';
COMMENT ON COLUMN esejur.matricula.curso_id IS 'Curso al que pertenece la matricula.';
COMMENT ON COLUMN esejur.matricula.estado IS 'Situacion de la matricula: pendiente, activa, vencida o cancelada.';
COMMENT ON COLUMN esejur.matricula.forma_ingreso IS 'Origen de la matricula: gratuita, por pago o administrativa.';
COMMENT ON COLUMN esejur.matricula.fecha_matricula IS 'Fecha y hora en que se registro la matricula.';
COMMENT ON COLUMN esejur.matricula.fecha_activacion IS 'Fecha y hora desde la que el acceso al curso quedo activo.';
COMMENT ON COLUMN esejur.matricula.fecha_vencimiento IS 'Fecha y hora de vencimiento del acceso, cuando exista.';
COMMENT ON COLUMN esejur.matricula.motivo_cancelacion IS 'Explicacion de la cancelacion de la matricula, cuando corresponda.';
COMMENT ON COLUMN esejur.matricula.creado_por_usuario_id IS 'Administrador que creo la matricula cuando el ingreso fue administrativo.';
COMMENT ON COLUMN esejur.matricula.creado_en IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN esejur.matricula.modificado_en IS 'Fecha y hora de la ultima modificacion del registro.';

COMMIT;
