-- ESEJUR - Version acumulativa hasta EP02 Publicacion y matricula
-- PostgreSQL 15+
-- Ejecutar sobre una base limpia. Incluye EP01 y EP02 en su definicion final.
-- Solo contiene tablas, columnas, llaves primarias, foraneas y de unicidad.

BEGIN;

-- =============================================================================
-- IDENTIDAD, CUENTAS Y ACCESO
-- =============================================================================

CREATE TABLE rol (
    rol_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(50) NOT NULL,
    nombre varchar(100) NOT NULL,
    descripcion text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_rol PRIMARY KEY (rol_id),
    CONSTRAINT uq_rol_codigo UNIQUE (codigo)
);
COMMENT ON TABLE rol IS 'Catalogo de roles disponibles en el sistema.';
COMMENT ON COLUMN rol.rol_id IS 'Identificador interno del rol.';
COMMENT ON COLUMN rol.codigo IS 'Codigo unico del rol.';
COMMENT ON COLUMN rol.nombre IS 'Nombre visible del rol.';
COMMENT ON COLUMN rol.descripcion IS 'Descripcion funcional del rol.';
COMMENT ON COLUMN rol.activo IS 'Indica si el rol puede asignarse.';
COMMENT ON COLUMN rol.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN rol.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE persona (
    persona_id bigint GENERATED BY DEFAULT AS IDENTITY,
    nombres varchar(120) NOT NULL,
    apellido_paterno varchar(80) NOT NULL,
    apellido_materno varchar(80),
    telefono varchar(30),
    documento_identidad varchar(30),
    foto_url text,
    cargo_profesional varchar(180),
    biografia_profesional text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_persona PRIMARY KEY (persona_id),
    CONSTRAINT uq_persona_documento UNIQUE (documento_identidad)
);
COMMENT ON TABLE persona IS 'Identidad unica de alumnos, administradores, docentes y firmantes.';
COMMENT ON COLUMN persona.persona_id IS 'Identificador interno de la persona.';
COMMENT ON COLUMN persona.nombres IS 'Nombres de la persona.';
COMMENT ON COLUMN persona.apellido_paterno IS 'Apellido paterno.';
COMMENT ON COLUMN persona.apellido_materno IS 'Apellido materno opcional.';
COMMENT ON COLUMN persona.telefono IS 'Telefono opcional.';
COMMENT ON COLUMN persona.documento_identidad IS 'Documento opcional; no se imprime en certificados.';
COMMENT ON COLUMN persona.foto_url IS 'Ubicacion de la fotografia opcional.';
COMMENT ON COLUMN persona.cargo_profesional IS 'Cargo o especialidad profesional.';
COMMENT ON COLUMN persona.biografia_profesional IS 'Resena profesional publica.';
COMMENT ON COLUMN persona.activo IS 'Indica si la persona puede utilizarse.';
COMMENT ON COLUMN persona.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN persona.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE usuario (
    usuario_id bigint GENERATED BY DEFAULT AS IDENTITY,
    persona_id bigint NOT NULL,
    correo varchar(254) NOT NULL,
    origen_registro varchar(20) NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    contrasena_hash text,
    google_subject varchar(255),
    requiere_cambio_contrasena boolean NOT NULL DEFAULT false,
    correo_verificado_en timestamptz,
    creado_por_usuario_id bigint,
    deshabilitado_en timestamptz,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_persona UNIQUE (persona_id),
    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT uq_usuario_google UNIQUE (google_subject),
    CONSTRAINT fk_usuario_persona FOREIGN KEY (persona_id) REFERENCES persona(persona_id),
    CONSTRAINT fk_usuario_creador FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE usuario IS 'Cuenta de acceso asociada a una persona.';
COMMENT ON COLUMN usuario.usuario_id IS 'Identificador interno de la cuenta.';
COMMENT ON COLUMN usuario.persona_id IS 'Persona propietaria de la cuenta.';
COMMENT ON COLUMN usuario.correo IS 'Correo unico usado para el acceso.';
COMMENT ON COLUMN usuario.origen_registro IS 'Origen de la cuenta: FORMULARIO, GOOGLE o ADMINISTRADOR.';
COMMENT ON COLUMN usuario.activo IS 'Indica si la cuenta puede acceder.';
COMMENT ON COLUMN usuario.contrasena_hash IS 'Contrasena almacenada de forma segura cuando corresponde.';
COMMENT ON COLUMN usuario.google_subject IS 'Identificador unico entregado por Google.';
COMMENT ON COLUMN usuario.requiere_cambio_contrasena IS 'Indica si debe cambiar la contrasena temporal.';
COMMENT ON COLUMN usuario.correo_verificado_en IS 'Fecha y hora de verificacion del correo.';
COMMENT ON COLUMN usuario.creado_por_usuario_id IS 'Administrador que creo la cuenta, si corresponde.';
COMMENT ON COLUMN usuario.deshabilitado_en IS 'Fecha y hora de deshabilitacion.';
COMMENT ON COLUMN usuario.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN usuario.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE usuario_rol (
    usuario_id bigint NOT NULL,
    rol_id bigint NOT NULL,
    es_principal boolean NOT NULL DEFAULT true,
    asignado_por_usuario_id bigint,
    asignado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id),
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (rol_id) REFERENCES rol(rol_id),
    CONSTRAINT fk_usuario_rol_asignador FOREIGN KEY (asignado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE usuario_rol IS 'Roles acumulables asignados a cada cuenta.';
COMMENT ON COLUMN usuario_rol.usuario_id IS 'Cuenta que recibe el rol.';
COMMENT ON COLUMN usuario_rol.rol_id IS 'Rol asignado.';
COMMENT ON COLUMN usuario_rol.es_principal IS 'Indica el rol principal; en esta version se usa un solo rol por cuenta.';
COMMENT ON COLUMN usuario_rol.asignado_por_usuario_id IS 'Administrador que realizo la asignacion.';
COMMENT ON COLUMN usuario_rol.asignado_en IS 'Fecha y hora de asignacion.';

CREATE TABLE codigo_verificacion_correo (
    codigo_verificacion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id bigint NOT NULL,
    codigo_hash text NOT NULL,
    estado_envio varchar(15) NOT NULL DEFAULT 'PENDIENTE',
    solicitado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utilizado_en timestamptz,
    invalidado_en timestamptz,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_codigo_verificacion PRIMARY KEY (codigo_verificacion_id),
    CONSTRAINT fk_codigo_verificacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE codigo_verificacion_correo IS 'Codigos emitidos para verificar el correo de una cuenta.';
COMMENT ON COLUMN codigo_verificacion_correo.codigo_verificacion_id IS 'Identificador del codigo.';
COMMENT ON COLUMN codigo_verificacion_correo.usuario_id IS 'Cuenta que solicito el codigo.';
COMMENT ON COLUMN codigo_verificacion_correo.codigo_hash IS 'Representacion segura del codigo.';
COMMENT ON COLUMN codigo_verificacion_correo.estado_envio IS 'Resultado del intento de envio.';
COMMENT ON COLUMN codigo_verificacion_correo.solicitado_en IS 'Fecha y hora de solicitud.';
COMMENT ON COLUMN codigo_verificacion_correo.utilizado_en IS 'Fecha y hora de uso correcto.';
COMMENT ON COLUMN codigo_verificacion_correo.invalidado_en IS 'Fecha y hora de invalidacion.';
COMMENT ON COLUMN codigo_verificacion_correo.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE token_recuperacion_acceso (
    token_recuperacion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id bigint NOT NULL,
    token_hash text NOT NULL,
    estado_envio varchar(15) NOT NULL DEFAULT 'PENDIENTE',
    solicitado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_en timestamptz NOT NULL,
    utilizado_en timestamptz,
    invalidado_en timestamptz,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_token_recuperacion PRIMARY KEY (token_recuperacion_id),
    CONSTRAINT fk_token_recuperacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE token_recuperacion_acceso IS 'Tokens de un solo uso para recuperar el acceso.';
COMMENT ON COLUMN token_recuperacion_acceso.token_recuperacion_id IS 'Identificador del token.';
COMMENT ON COLUMN token_recuperacion_acceso.usuario_id IS 'Cuenta que solicito la recuperacion.';
COMMENT ON COLUMN token_recuperacion_acceso.token_hash IS 'Representacion segura del token.';
COMMENT ON COLUMN token_recuperacion_acceso.estado_envio IS 'Resultado del intento de envio.';
COMMENT ON COLUMN token_recuperacion_acceso.solicitado_en IS 'Fecha y hora de solicitud.';
COMMENT ON COLUMN token_recuperacion_acceso.expira_en IS 'Fecha y hora de expiracion.';
COMMENT ON COLUMN token_recuperacion_acceso.utilizado_en IS 'Fecha y hora de uso correcto.';
COMMENT ON COLUMN token_recuperacion_acceso.invalidado_en IS 'Fecha y hora de invalidacion.';
COMMENT ON COLUMN token_recuperacion_acceso.modificado_en IS 'Fecha y hora de ultima modificacion.';

-- =============================================================================
-- CATALOGOS Y CONFIGURACION
-- =============================================================================

CREATE TABLE tipo_curso (
    tipo_curso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(50) NOT NULL,
    nombre varchar(120) NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    orden integer NOT NULL DEFAULT 0,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tipo_curso PRIMARY KEY (tipo_curso_id),
    CONSTRAINT uq_tipo_curso_codigo UNIQUE (codigo)
);
COMMENT ON TABLE tipo_curso IS 'Tipos comerciales y academicos de curso.';
COMMENT ON COLUMN tipo_curso.tipo_curso_id IS 'Identificador del tipo.';
COMMENT ON COLUMN tipo_curso.codigo IS 'Codigo unico.';
COMMENT ON COLUMN tipo_curso.nombre IS 'Nombre visible.';
COMMENT ON COLUMN tipo_curso.activo IS 'Indica si puede seleccionarse.';
COMMENT ON COLUMN tipo_curso.orden IS 'Orden de presentacion.';
COMMENT ON COLUMN tipo_curso.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN tipo_curso.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE categoria_tematica (
    categoria_tematica_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(50) NOT NULL,
    nombre varchar(120) NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    orden integer NOT NULL DEFAULT 0,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_categoria_tematica PRIMARY KEY (categoria_tematica_id),
    CONSTRAINT uq_categoria_tematica_codigo UNIQUE (codigo)
);
COMMENT ON TABLE categoria_tematica IS 'Categorias usadas para organizar y filtrar cursos.';
COMMENT ON COLUMN categoria_tematica.categoria_tematica_id IS 'Identificador de la categoria.';
COMMENT ON COLUMN categoria_tematica.codigo IS 'Codigo unico.';
COMMENT ON COLUMN categoria_tematica.nombre IS 'Nombre visible.';
COMMENT ON COLUMN categoria_tematica.activo IS 'Indica si puede seleccionarse.';
COMMENT ON COLUMN categoria_tematica.orden IS 'Orden de presentacion.';
COMMENT ON COLUMN categoria_tematica.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN categoria_tematica.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE entidad_certificadora (
    entidad_certificadora_id bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(200) NOT NULL,
    logo_url text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_entidad_certificadora PRIMARY KEY (entidad_certificadora_id),
    CONSTRAINT uq_entidad_certificadora_nombre UNIQUE (nombre)
);
COMMENT ON TABLE entidad_certificadora IS 'Entidades disponibles para refrendar certificados.';
COMMENT ON COLUMN entidad_certificadora.entidad_certificadora_id IS 'Identificador de la entidad.';
COMMENT ON COLUMN entidad_certificadora.nombre IS 'Nombre institucional.';
COMMENT ON COLUMN entidad_certificadora.logo_url IS 'Ubicacion del logotipo.';
COMMENT ON COLUMN entidad_certificadora.activo IS 'Indica si puede seleccionarse.';
COMMENT ON COLUMN entidad_certificadora.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN entidad_certificadora.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE estado_curso (
    estado_curso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(20) NOT NULL,
    nombre varchar(80) NOT NULL,
    descripcion text NOT NULL,
    orden integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_estado_curso PRIMARY KEY (estado_curso_id),
    CONSTRAINT uq_estado_curso_codigo UNIQUE (codigo)
);
COMMENT ON TABLE estado_curso IS 'Estados del ciclo de vida de un curso.';
COMMENT ON COLUMN estado_curso.estado_curso_id IS 'Identificador del estado.';
COMMENT ON COLUMN estado_curso.codigo IS 'Codigo unico del estado.';
COMMENT ON COLUMN estado_curso.nombre IS 'Nombre visible.';
COMMENT ON COLUMN estado_curso.descripcion IS 'Significado funcional.';
COMMENT ON COLUMN estado_curso.orden IS 'Orden del ciclo ordinario.';
COMMENT ON COLUMN estado_curso.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN estado_curso.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE tipo_material (
    tipo_material_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(30) NOT NULL,
    nombre varchar(100) NOT NULL,
    descripcion text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tipo_material PRIMARY KEY (tipo_material_id),
    CONSTRAINT uq_tipo_material_codigo UNIQUE (codigo)
);
COMMENT ON TABLE tipo_material IS 'Tipos funcionales de material permitidos en una leccion.';
COMMENT ON COLUMN tipo_material.tipo_material_id IS 'Identificador del tipo de material.';
COMMENT ON COLUMN tipo_material.codigo IS 'Codigo unico.';
COMMENT ON COLUMN tipo_material.nombre IS 'Nombre visible.';
COMMENT ON COLUMN tipo_material.descripcion IS 'Uso esperado del material.';
COMMENT ON COLUMN tipo_material.activo IS 'Indica si puede seleccionarse.';
COMMENT ON COLUMN tipo_material.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN tipo_material.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE regla_archivo (
    regla_archivo_id bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_material_id bigint NOT NULL,
    extension varchar(15) NOT NULL,
    tamano_maximo_bytes bigint NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_regla_archivo PRIMARY KEY (regla_archivo_id),
    CONSTRAINT uq_regla_archivo_tipo_extension UNIQUE (tipo_material_id, extension),
    CONSTRAINT fk_regla_archivo_tipo FOREIGN KEY (tipo_material_id) REFERENCES tipo_material(tipo_material_id)
);
COMMENT ON TABLE regla_archivo IS 'Extensiones y tamanos permitidos por tipo de material.';
COMMENT ON COLUMN regla_archivo.regla_archivo_id IS 'Identificador de la regla.';
COMMENT ON COLUMN regla_archivo.tipo_material_id IS 'Tipo de material regulado.';
COMMENT ON COLUMN regla_archivo.extension IS 'Extension admitida sin punto.';
COMMENT ON COLUMN regla_archivo.tamano_maximo_bytes IS 'Tamano maximo permitido en bytes.';
COMMENT ON COLUMN regla_archivo.activo IS 'Indica si la regla se aplica.';
COMMENT ON COLUMN regla_archivo.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN regla_archivo.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE configuracion_institucional (
    configuracion_institucional_id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(80) NOT NULL,
    valor text NOT NULL,
    descripcion text,
    modificado_por_usuario_id bigint,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_configuracion_institucional PRIMARY KEY (configuracion_institucional_id),
    CONSTRAINT uq_configuracion_institucional_codigo UNIQUE (codigo),
    CONSTRAINT fk_configuracion_modificador FOREIGN KEY (modificado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE configuracion_institucional IS 'Valores institucionales reutilizados en documentos y procesos.';
COMMENT ON COLUMN configuracion_institucional.configuracion_institucional_id IS 'Identificador de la configuracion.';
COMMENT ON COLUMN configuracion_institucional.codigo IS 'Codigo unico del valor.';
COMMENT ON COLUMN configuracion_institucional.valor IS 'Valor vigente.';
COMMENT ON COLUMN configuracion_institucional.descripcion IS 'Finalidad del valor.';
COMMENT ON COLUMN configuracion_institucional.modificado_por_usuario_id IS 'Administrador que realizo el ultimo cambio.';
COMMENT ON COLUMN configuracion_institucional.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN configuracion_institucional.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE firmante (
    firmante_id bigint GENERATED BY DEFAULT AS IDENTITY,
    persona_id bigint NOT NULL,
    cargo_firma varchar(180) NOT NULL,
    imagen_firma_url text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_firmante PRIMARY KEY (firmante_id),
    CONSTRAINT uq_firmante_persona UNIQUE (persona_id),
    CONSTRAINT fk_firmante_persona FOREIGN KEY (persona_id) REFERENCES persona(persona_id)
);
COMMENT ON TABLE firmante IS 'Personas autorizadas para firmar certificados.';
COMMENT ON COLUMN firmante.firmante_id IS 'Identificador del firmante.';
COMMENT ON COLUMN firmante.persona_id IS 'Persona que firma.';
COMMENT ON COLUMN firmante.cargo_firma IS 'Cargo que aparece junto a la firma.';
COMMENT ON COLUMN firmante.imagen_firma_url IS 'Ubicacion de la imagen de firma.';
COMMENT ON COLUMN firmante.activo IS 'Indica si puede asignarse a cursos.';
COMMENT ON COLUMN firmante.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN firmante.modificado_en IS 'Fecha y hora de ultima modificacion.';

-- =============================================================================
-- CURSOS, CONTENIDO Y EVALUACION
-- =============================================================================

CREATE TABLE curso (
    curso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    curso_origen_id bigint,
    url_amigable varchar(180) NOT NULL,
    titulo varchar(220) NOT NULL,
    descripcion text,
    imagen_portada_url text,
    tipo_curso_id bigint,
    categoria_tematica_id bigint,
    entidad_certificadora_id bigint,
    modalidad varchar(15),
    tipo_venta varchar(10),
    estado_curso_id bigint NOT NULL,
    destacado boolean NOT NULL DEFAULT false,
    precio_regular numeric(10,2) NOT NULL DEFAULT 0,
    precio_promocional numeric(10,2),
    promocion_inicio_en timestamptz,
    promocion_fin_en timestamptz,
    fecha_inicio date,
    fecha_fin date,
    fecha_cierre_matricula date,
    cupo_maximo integer,
    horas_academicas numeric(8,2),
    vigencia_acceso_dias integer,
    beneficios text[] NOT NULL DEFAULT ARRAY[]::text[],
    creado_por_usuario_id bigint,
    publicado_en timestamptz,
    reglas_bloqueadas_en timestamptz,
    cerrado_en timestamptz,
    cancelado_en timestamptz,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_curso PRIMARY KEY (curso_id),
    CONSTRAINT uq_curso_url_amigable UNIQUE (url_amigable),
    CONSTRAINT fk_curso_origen FOREIGN KEY (curso_origen_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_curso_tipo FOREIGN KEY (tipo_curso_id) REFERENCES tipo_curso(tipo_curso_id),
    CONSTRAINT fk_curso_categoria FOREIGN KEY (categoria_tematica_id) REFERENCES categoria_tematica(categoria_tematica_id),
    CONSTRAINT fk_curso_entidad FOREIGN KEY (entidad_certificadora_id) REFERENCES entidad_certificadora(entidad_certificadora_id),
    CONSTRAINT fk_curso_estado FOREIGN KEY (estado_curso_id) REFERENCES estado_curso(estado_curso_id),
    CONSTRAINT fk_curso_creador FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE curso IS 'Oferta academica publicable, vendible y reutilizable de ESEJUR.';
COMMENT ON COLUMN curso.curso_id IS 'Identificador del curso.';
COMMENT ON COLUMN curso.curso_origen_id IS 'Curso del que se duplico el registro.';
COMMENT ON COLUMN curso.url_amigable IS 'Segmento unico usado en la URL publica.';
COMMENT ON COLUMN curso.titulo IS 'Nombre comercial del curso.';
COMMENT ON COLUMN curso.descripcion IS 'Presentacion detallada.';
COMMENT ON COLUMN curso.imagen_portada_url IS 'Ubicacion de la portada.';
COMMENT ON COLUMN curso.tipo_curso_id IS 'Tipo del curso.';
COMMENT ON COLUMN curso.categoria_tematica_id IS 'Categoria principal.';
COMMENT ON COLUMN curso.entidad_certificadora_id IS 'Entidad que refrenda, cuando corresponda.';
COMMENT ON COLUMN curso.modalidad IS 'Modalidad VIRTUAL, EN_VIVO o HIBRIDO.';
COMMENT ON COLUMN curso.tipo_venta IS 'Condicion PAGADO o GRATUITO.';
COMMENT ON COLUMN curso.estado_curso_id IS 'Estado actual del ciclo de vida.';
COMMENT ON COLUMN curso.destacado IS 'Indica si se resalta en el catalogo.';
COMMENT ON COLUMN curso.precio_regular IS 'Precio ordinario confirmado al iniciar un pago.';
COMMENT ON COLUMN curso.precio_promocional IS 'Precio promocional opcional.';
COMMENT ON COLUMN curso.promocion_inicio_en IS 'Inicio de vigencia de la promocion.';
COMMENT ON COLUMN curso.promocion_fin_en IS 'Fin de vigencia de la promocion.';
COMMENT ON COLUMN curso.fecha_inicio IS 'Inicio academico para vivo o hibrido.';
COMMENT ON COLUMN curso.fecha_fin IS 'Fin academico para vivo o hibrido; virtual no lo requiere.';
COMMENT ON COLUMN curso.fecha_cierre_matricula IS 'Ultimo dia para matricularse cuando aplica.';
COMMENT ON COLUMN curso.cupo_maximo IS 'Cupos pagados disponibles en vivo o hibrido.';
COMMENT ON COLUMN curso.horas_academicas IS 'Duracion academica comunicada.';
COMMENT ON COLUMN curso.vigencia_acceso_dias IS 'Dias de acceso posteriores a la activacion cuando existe limite.';
COMMENT ON COLUMN curso.beneficios IS 'Beneficios mostrados en la ficha publica.';
COMMENT ON COLUMN curso.creado_por_usuario_id IS 'Administrador creador.';
COMMENT ON COLUMN curso.publicado_en IS 'Fecha y hora de publicacion.';
COMMENT ON COLUMN curso.reglas_bloqueadas_en IS 'Momento desde el cual las reglas academicas no pueden cambiarse.';
COMMENT ON COLUMN curso.cerrado_en IS 'Fecha y hora de cierre ordinario.';
COMMENT ON COLUMN curso.cancelado_en IS 'Fecha y hora de cancelacion excepcional.';
COMMENT ON COLUMN curso.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN curso.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE curso_docente (
    curso_id bigint NOT NULL,
    persona_id bigint NOT NULL,
    orden integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_curso_docente PRIMARY KEY (curso_id, persona_id),
    CONSTRAINT uq_curso_docente_orden UNIQUE (curso_id, orden),
    CONSTRAINT fk_curso_docente_curso FOREIGN KEY (curso_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_curso_docente_persona FOREIGN KEY (persona_id) REFERENCES persona(persona_id)
);
COMMENT ON TABLE curso_docente IS 'Docentes ordenados que participan en cada curso; no requieren cuenta.';
COMMENT ON COLUMN curso_docente.curso_id IS 'Curso asignado.';
COMMENT ON COLUMN curso_docente.persona_id IS 'Persona docente.';
COMMENT ON COLUMN curso_docente.orden IS 'Orden de presentacion.';
COMMENT ON COLUMN curso_docente.creado_en IS 'Fecha y hora de asignacion.';

CREATE TABLE curso_firmante (
    curso_id bigint NOT NULL,
    firmante_id bigint NOT NULL,
    orden integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_curso_firmante PRIMARY KEY (curso_id, firmante_id),
    CONSTRAINT uq_curso_firmante_orden UNIQUE (curso_id, orden),
    CONSTRAINT fk_curso_firmante_curso FOREIGN KEY (curso_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_curso_firmante_firmante FOREIGN KEY (firmante_id) REFERENCES firmante(firmante_id)
);
COMMENT ON TABLE curso_firmante IS 'Firmantes ordenados configurados para el certificado de un curso.';
COMMENT ON COLUMN curso_firmante.curso_id IS 'Curso configurado.';
COMMENT ON COLUMN curso_firmante.firmante_id IS 'Firmante asignado.';
COMMENT ON COLUMN curso_firmante.orden IS 'Orden de aparicion.';
COMMENT ON COLUMN curso_firmante.creado_en IS 'Fecha y hora de asignacion.';

CREATE TABLE regla_curso (
    regla_curso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    curso_id bigint NOT NULL,
    requiere_examenes boolean NOT NULL DEFAULT true,
    requiere_progreso boolean NOT NULL DEFAULT true,
    requiere_asistencia boolean NOT NULL DEFAULT false,
    nota_minima numeric(5,2) NOT NULL DEFAULT 12,
    nota_refrendado numeric(5,2) NOT NULL DEFAULT 14,
    progreso_minimo numeric(5,2) NOT NULL DEFAULT 80,
    umbral_video numeric(5,2) NOT NULL DEFAULT 50,
    asistencia_minima numeric(5,2) NOT NULL DEFAULT 80,
    secuencia_obligatoria boolean NOT NULL DEFAULT true,
    dias_espera_certificado integer NOT NULL DEFAULT 0,
    bloqueado_en timestamptz,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_regla_curso PRIMARY KEY (regla_curso_id),
    CONSTRAINT uq_regla_curso_curso UNIQUE (curso_id),
    CONSTRAINT fk_regla_curso_curso FOREIGN KEY (curso_id) REFERENCES curso(curso_id)
);
COMMENT ON TABLE regla_curso IS 'Reglas academicas y de certificacion propias de cada curso.';
COMMENT ON COLUMN regla_curso.regla_curso_id IS 'Identificador de la configuracion.';
COMMENT ON COLUMN regla_curso.curso_id IS 'Curso configurado.';
COMMENT ON COLUMN regla_curso.requiere_examenes IS 'Indica si la aprobacion exige examenes.';
COMMENT ON COLUMN regla_curso.requiere_progreso IS 'Indica si exige progreso minimo.';
COMMENT ON COLUMN regla_curso.requiere_asistencia IS 'Indica si exige asistencia; no aplica a virtual.';
COMMENT ON COLUMN regla_curso.nota_minima IS 'Nota minima general.';
COMMENT ON COLUMN regla_curso.nota_refrendado IS 'Nota minima cuando existe refrendo.';
COMMENT ON COLUMN regla_curso.progreso_minimo IS 'Porcentaje minimo de progreso.';
COMMENT ON COLUMN regla_curso.umbral_video IS 'Porcentaje de video necesario para completar una leccion.';
COMMENT ON COLUMN regla_curso.asistencia_minima IS 'Porcentaje minimo de asistencia cuando aplica.';
COMMENT ON COLUMN regla_curso.secuencia_obligatoria IS 'Indica si modulos y lecciones avanzan en orden.';
COMMENT ON COLUMN regla_curso.dias_espera_certificado IS 'Dias de espera antes de emitir el certificado; cero es inmediato.';
COMMENT ON COLUMN regla_curso.bloqueado_en IS 'Momento desde el cual la configuracion no cambia.';
COMMENT ON COLUMN regla_curso.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN regla_curso.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE historial_estado_curso (
    historial_estado_curso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    curso_id bigint NOT NULL,
    estado_anterior_id bigint,
    estado_nuevo_id bigint NOT NULL,
    motivo text,
    realizado_por_usuario_id bigint,
    realizado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_historial_estado_curso PRIMARY KEY (historial_estado_curso_id),
    CONSTRAINT fk_historial_curso FOREIGN KEY (curso_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_historial_curso_anterior FOREIGN KEY (estado_anterior_id) REFERENCES estado_curso(estado_curso_id),
    CONSTRAINT fk_historial_curso_nuevo FOREIGN KEY (estado_nuevo_id) REFERENCES estado_curso(estado_curso_id),
    CONSTRAINT fk_historial_curso_usuario FOREIGN KEY (realizado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE historial_estado_curso IS 'Trazabilidad de cambios de estado de los cursos.';
COMMENT ON COLUMN historial_estado_curso.historial_estado_curso_id IS 'Identificador del cambio.';
COMMENT ON COLUMN historial_estado_curso.curso_id IS 'Curso afectado.';
COMMENT ON COLUMN historial_estado_curso.estado_anterior_id IS 'Estado previo, ausente al crear.';
COMMENT ON COLUMN historial_estado_curso.estado_nuevo_id IS 'Estado resultante.';
COMMENT ON COLUMN historial_estado_curso.motivo IS 'Motivo opcional.';
COMMENT ON COLUMN historial_estado_curso.realizado_por_usuario_id IS 'Administrador responsable.';
COMMENT ON COLUMN historial_estado_curso.realizado_en IS 'Fecha y hora del cambio.';

CREATE TABLE modulo (
    modulo_id bigint GENERATED BY DEFAULT AS IDENTITY,
    modulo_origen_id bigint,
    curso_id bigint NOT NULL,
    titulo varchar(220) NOT NULL,
    descripcion text,
    orden integer NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_modulo PRIMARY KEY (modulo_id),
    CONSTRAINT uq_modulo_curso_orden UNIQUE (curso_id, orden),
    CONSTRAINT fk_modulo_origen FOREIGN KEY (modulo_origen_id) REFERENCES modulo(modulo_id),
    CONSTRAINT fk_modulo_curso FOREIGN KEY (curso_id) REFERENCES curso(curso_id)
);
COMMENT ON TABLE modulo IS 'Bloques ordenados que estructuran el contenido de un curso.';
COMMENT ON COLUMN modulo.modulo_id IS 'Identificador del modulo.';
COMMENT ON COLUMN modulo.modulo_origen_id IS 'Modulo del que se reutilizo el contenido.';
COMMENT ON COLUMN modulo.curso_id IS 'Curso propietario.';
COMMENT ON COLUMN modulo.titulo IS 'Titulo del modulo.';
COMMENT ON COLUMN modulo.descripcion IS 'Descripcion opcional.';
COMMENT ON COLUMN modulo.orden IS 'Orden dentro del curso.';
COMMENT ON COLUMN modulo.activo IS 'Indica si permanece disponible.';
COMMENT ON COLUMN modulo.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN modulo.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE leccion (
    leccion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    leccion_origen_id bigint,
    modulo_id bigint NOT NULL,
    titulo varchar(220) NOT NULL,
    descripcion text,
    orden integer NOT NULL,
    tipo varchar(10) NOT NULL,
    estado varchar(15) NOT NULL,
    es_obligatoria boolean NOT NULL DEFAULT true,
    es_vista_previa boolean NOT NULL DEFAULT false,
    fecha_hora_inicio timestamptz,
    fecha_hora_fin timestamptz,
    enlace_reunion text,
    motivo_cancelacion text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_leccion PRIMARY KEY (leccion_id),
    CONSTRAINT uq_leccion_modulo_orden UNIQUE (modulo_id, orden),
    CONSTRAINT fk_leccion_origen FOREIGN KEY (leccion_origen_id) REFERENCES leccion(leccion_id),
    CONSTRAINT fk_leccion_modulo FOREIGN KEY (modulo_id) REFERENCES modulo(modulo_id)
);
COMMENT ON TABLE leccion IS 'Lecciones grabadas o sesiones en vivo ordenadas en un modulo.';
COMMENT ON COLUMN leccion.leccion_id IS 'Identificador de la leccion.';
COMMENT ON COLUMN leccion.leccion_origen_id IS 'Leccion de la que se reutilizo el contenido.';
COMMENT ON COLUMN leccion.modulo_id IS 'Modulo propietario.';
COMMENT ON COLUMN leccion.titulo IS 'Titulo de la leccion.';
COMMENT ON COLUMN leccion.descripcion IS 'Descripcion opcional.';
COMMENT ON COLUMN leccion.orden IS 'Orden dentro del modulo.';
COMMENT ON COLUMN leccion.tipo IS 'Tipo GRABADA o EN_VIVO.';
COMMENT ON COLUMN leccion.estado IS 'Estado de preparacion o realizacion.';
COMMENT ON COLUMN leccion.es_obligatoria IS 'Indica si debe completarse.';
COMMENT ON COLUMN leccion.es_vista_previa IS 'Indica si puede verse sin matricula.';
COMMENT ON COLUMN leccion.fecha_hora_inicio IS 'Inicio programado para una sesion en vivo.';
COMMENT ON COLUMN leccion.fecha_hora_fin IS 'Fin programado para una sesion en vivo.';
COMMENT ON COLUMN leccion.enlace_reunion IS 'Enlace de acceso a la sesion.';
COMMENT ON COLUMN leccion.motivo_cancelacion IS 'Motivo cuando la sesion se cancela.';
COMMENT ON COLUMN leccion.activo IS 'Indica si permanece disponible.';
COMMENT ON COLUMN leccion.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN leccion.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE recurso (
    recurso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_material_id bigint NOT NULL,
    tipo varchar(15) NOT NULL,
    origen varchar(20) NOT NULL,
    referencia text NOT NULL,
    nombre_archivo varchar(255),
    tipo_mime varchar(150),
    tamano_bytes bigint,
    duracion_segundos integer,
    duracion_detectada boolean NOT NULL DEFAULT false,
    youtube_no_listado_confirmado boolean,
    creado_por_usuario_id bigint,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_recurso PRIMARY KEY (recurso_id),
    CONSTRAINT fk_recurso_tipo_material FOREIGN KEY (tipo_material_id) REFERENCES tipo_material(tipo_material_id),
    CONSTRAINT fk_recurso_creador FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE recurso IS 'Archivos, videos y enlaces reutilizables en las lecciones.';
COMMENT ON COLUMN recurso.recurso_id IS 'Identificador del recurso.';
COMMENT ON COLUMN recurso.tipo_material_id IS 'Tipo funcional del material.';
COMMENT ON COLUMN recurso.tipo IS 'Naturaleza tecnica: VIDEO, ARCHIVO o ENLACE.';
COMMENT ON COLUMN recurso.origen IS 'Procedencia: SUBIDO, YOUTUBE o EXTERNO.';
COMMENT ON COLUMN recurso.referencia IS 'Ruta o enlace del contenido.';
COMMENT ON COLUMN recurso.nombre_archivo IS 'Nombre original cuando fue subido.';
COMMENT ON COLUMN recurso.tipo_mime IS 'Tipo MIME detectado.';
COMMENT ON COLUMN recurso.tamano_bytes IS 'Tamano en bytes.';
COMMENT ON COLUMN recurso.duracion_segundos IS 'Duracion calculada solo para video subido.';
COMMENT ON COLUMN recurso.duracion_detectada IS 'Indica si la duracion fue calculada.';
COMMENT ON COLUMN recurso.youtube_no_listado_confirmado IS 'Confirmacion del administrador para un video de YouTube.';
COMMENT ON COLUMN recurso.creado_por_usuario_id IS 'Administrador que registro el recurso.';
COMMENT ON COLUMN recurso.activo IS 'Indica si el recurso sigue disponible.';
COMMENT ON COLUMN recurso.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN recurso.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE material_leccion (
    material_leccion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    leccion_id bigint NOT NULL,
    recurso_id bigint NOT NULL,
    titulo varchar(220) NOT NULL,
    orden integer NOT NULL,
    permite_descarga boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_material_leccion PRIMARY KEY (material_leccion_id),
    CONSTRAINT uq_material_leccion_recurso UNIQUE (leccion_id, recurso_id),
    CONSTRAINT uq_material_leccion_orden UNIQUE (leccion_id, orden),
    CONSTRAINT fk_material_leccion_leccion FOREIGN KEY (leccion_id) REFERENCES leccion(leccion_id),
    CONSTRAINT fk_material_leccion_recurso FOREIGN KEY (recurso_id) REFERENCES recurso(recurso_id)
);
COMMENT ON TABLE material_leccion IS 'Materiales ordenados asociados a una leccion.';
COMMENT ON COLUMN material_leccion.material_leccion_id IS 'Identificador de la asociacion.';
COMMENT ON COLUMN material_leccion.leccion_id IS 'Leccion propietaria.';
COMMENT ON COLUMN material_leccion.recurso_id IS 'Recurso utilizado.';
COMMENT ON COLUMN material_leccion.titulo IS 'Titulo mostrado al alumno.';
COMMENT ON COLUMN material_leccion.orden IS 'Orden dentro de la leccion.';
COMMENT ON COLUMN material_leccion.permite_descarga IS 'Indica si el alumno puede descargarlo.';
COMMENT ON COLUMN material_leccion.activo IS 'Indica si permanece visible.';
COMMENT ON COLUMN material_leccion.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN material_leccion.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE examen (
    examen_id bigint GENERATED BY DEFAULT AS IDENTITY,
    examen_origen_id bigint,
    curso_id bigint NOT NULL,
    modulo_id bigint,
    titulo varchar(220) NOT NULL,
    descripcion text,
    finalidad varchar(15) NOT NULL,
    orden integer NOT NULL,
    maximo_intentos integer,
    tiempo_limite_minutos integer,
    barajar_preguntas boolean NOT NULL DEFAULT false,
    barajar_opciones boolean NOT NULL DEFAULT false,
    mostrar_respuestas boolean NOT NULL DEFAULT true,
    fecha_habilitacion timestamptz,
    bloquea_siguiente_modulo boolean NOT NULL DEFAULT false,
    dias_revision integer NOT NULL DEFAULT 3,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_examen PRIMARY KEY (examen_id),
    CONSTRAINT uq_examen_curso_titulo UNIQUE (curso_id, titulo),
    CONSTRAINT fk_examen_origen FOREIGN KEY (examen_origen_id) REFERENCES examen(examen_id),
    CONSTRAINT fk_examen_curso FOREIGN KEY (curso_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_examen_modulo FOREIGN KEY (modulo_id) REFERENCES modulo(modulo_id)
);
COMMENT ON TABLE examen IS 'Configuracion de evaluaciones por modulo o finales.';
COMMENT ON COLUMN examen.examen_id IS 'Identificador del examen.';
COMMENT ON COLUMN examen.examen_origen_id IS 'Examen del que se reutilizo la configuracion.';
COMMENT ON COLUMN examen.curso_id IS 'Curso propietario.';
COMMENT ON COLUMN examen.modulo_id IS 'Modulo evaluado; vacio para examen final.';
COMMENT ON COLUMN examen.titulo IS 'Titulo visible.';
COMMENT ON COLUMN examen.descripcion IS 'Instrucciones opcionales.';
COMMENT ON COLUMN examen.finalidad IS 'Finalidad MODULO o FINAL.';
COMMENT ON COLUMN examen.orden IS 'Orden dentro del curso.';
COMMENT ON COLUMN examen.maximo_intentos IS 'Cantidad maxima de intentos; vacio significa sin limite.';
COMMENT ON COLUMN examen.tiempo_limite_minutos IS 'Tiempo maximo; vacio significa sin limite.';
COMMENT ON COLUMN examen.barajar_preguntas IS 'Indica si cambia el orden de preguntas.';
COMMENT ON COLUMN examen.barajar_opciones IS 'Indica si cambia el orden de alternativas.';
COMMENT ON COLUMN examen.mostrar_respuestas IS 'Indica si el resultado muestra las respuestas.';
COMMENT ON COLUMN examen.fecha_habilitacion IS 'Fecha opcional para habilitarlo en vivo o hibrido.';
COMMENT ON COLUMN examen.bloquea_siguiente_modulo IS 'Indica si debe aprobarse para continuar.';
COMMENT ON COLUMN examen.dias_revision IS 'Plazo maximo de calificacion para respuestas abiertas.';
COMMENT ON COLUMN examen.activo IS 'Indica si permanece disponible.';
COMMENT ON COLUMN examen.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN examen.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE pregunta (
    pregunta_id bigint GENERATED BY DEFAULT AS IDENTITY,
    examen_id bigint NOT NULL,
    tipo varchar(20) NOT NULL,
    enunciado text NOT NULL,
    puntaje numeric(6,2) NOT NULL,
    orden integer NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pregunta PRIMARY KEY (pregunta_id),
    CONSTRAINT uq_pregunta_examen_orden UNIQUE (examen_id, orden),
    CONSTRAINT fk_pregunta_examen FOREIGN KEY (examen_id) REFERENCES examen(examen_id)
);
COMMENT ON TABLE pregunta IS 'Preguntas objetivas o abiertas que componen un examen.';
COMMENT ON COLUMN pregunta.pregunta_id IS 'Identificador de la pregunta.';
COMMENT ON COLUMN pregunta.examen_id IS 'Examen propietario.';
COMMENT ON COLUMN pregunta.tipo IS 'Tipo OPCION_UNICA, OPCION_MULTIPLE o ABIERTA.';
COMMENT ON COLUMN pregunta.enunciado IS 'Texto de la pregunta.';
COMMENT ON COLUMN pregunta.puntaje IS 'Puntaje maximo.';
COMMENT ON COLUMN pregunta.orden IS 'Orden dentro del examen.';
COMMENT ON COLUMN pregunta.activo IS 'Indica si forma parte del examen.';
COMMENT ON COLUMN pregunta.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN pregunta.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE opcion_pregunta (
    opcion_pregunta_id bigint GENERATED BY DEFAULT AS IDENTITY,
    pregunta_id bigint NOT NULL,
    texto text NOT NULL,
    es_correcta boolean NOT NULL DEFAULT false,
    orden integer NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_opcion_pregunta PRIMARY KEY (opcion_pregunta_id),
    CONSTRAINT uq_opcion_pregunta_orden UNIQUE (pregunta_id, orden),
    CONSTRAINT fk_opcion_pregunta_pregunta FOREIGN KEY (pregunta_id) REFERENCES pregunta(pregunta_id)
);
COMMENT ON TABLE opcion_pregunta IS 'Alternativas configuradas para preguntas objetivas.';
COMMENT ON COLUMN opcion_pregunta.opcion_pregunta_id IS 'Identificador de la alternativa.';
COMMENT ON COLUMN opcion_pregunta.pregunta_id IS 'Pregunta propietaria.';
COMMENT ON COLUMN opcion_pregunta.texto IS 'Contenido de la alternativa.';
COMMENT ON COLUMN opcion_pregunta.es_correcta IS 'Indica si integra la respuesta correcta.';
COMMENT ON COLUMN opcion_pregunta.orden IS 'Orden de configuracion.';
COMMENT ON COLUMN opcion_pregunta.activo IS 'Indica si permanece disponible.';
COMMENT ON COLUMN opcion_pregunta.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN opcion_pregunta.modificado_en IS 'Fecha y hora de ultima modificacion.';

-- =============================================================================
-- MATRICULA, PAGO Y NOTIFICACION
-- =============================================================================

CREATE TABLE matricula (
    matricula_id bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id bigint NOT NULL,
    curso_id bigint NOT NULL,
    estado varchar(20) NOT NULL,
    forma_ingreso varchar(25) NOT NULL,
    fecha_matricula timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_activacion timestamptz,
    fecha_vencimiento timestamptz,
    fecha_finalizacion timestamptz,
    motivo_cancelacion text,
    cancelada_en timestamptz,
    cancelada_por_usuario_id bigint,
    creado_por_usuario_id bigint,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_matricula PRIMARY KEY (matricula_id),
    CONSTRAINT uq_matricula_usuario_curso UNIQUE (usuario_id, curso_id),
    CONSTRAINT fk_matricula_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (curso_id) REFERENCES curso(curso_id),
    CONSTRAINT fk_matricula_cancelador FOREIGN KEY (cancelada_por_usuario_id) REFERENCES usuario(usuario_id),
    CONSTRAINT fk_matricula_creador FOREIGN KEY (creado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE matricula IS 'Relacion de un alumno con un curso y su acceso vigente.';
COMMENT ON COLUMN matricula.matricula_id IS 'Identificador de la matricula.';
COMMENT ON COLUMN matricula.usuario_id IS 'Cuenta con rol ALUMNO matriculada.';
COMMENT ON COLUMN matricula.curso_id IS 'Curso adquirido o asignado.';
COMMENT ON COLUMN matricula.estado IS 'Estado PENDIENTE_PAGO, ACTIVA, FINALIZADA, VENCIDA o CANCELADA.';
COMMENT ON COLUMN matricula.forma_ingreso IS 'Origen PAGO_EN_LINEA, ADMINISTRADOR, GRATUITA o EXONERADA.';
COMMENT ON COLUMN matricula.fecha_matricula IS 'Fecha y hora de registro.';
COMMENT ON COLUMN matricula.fecha_activacion IS 'Momento en que obtuvo acceso.';
COMMENT ON COLUMN matricula.fecha_vencimiento IS 'Fin del acceso cuando existe vigencia.';
COMMENT ON COLUMN matricula.fecha_finalizacion IS 'Momento en que termino el curso.';
COMMENT ON COLUMN matricula.motivo_cancelacion IS 'Justificacion de la cancelacion.';
COMMENT ON COLUMN matricula.cancelada_en IS 'Fecha y hora de cancelacion.';
COMMENT ON COLUMN matricula.cancelada_por_usuario_id IS 'Administrador que cancelo la matricula.';
COMMENT ON COLUMN matricula.creado_por_usuario_id IS 'Administrador que realizo una asignacion manual.';
COMMENT ON COLUMN matricula.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN matricula.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE historial_estado_matricula (
    historial_estado_matricula_id bigint GENERATED BY DEFAULT AS IDENTITY,
    matricula_id bigint NOT NULL,
    estado_anterior varchar(20),
    estado_nuevo varchar(20) NOT NULL,
    motivo text,
    realizado_por_usuario_id bigint,
    realizado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_historial_estado_matricula PRIMARY KEY (historial_estado_matricula_id),
    CONSTRAINT fk_historial_matricula FOREIGN KEY (matricula_id) REFERENCES matricula(matricula_id),
    CONSTRAINT fk_historial_matricula_usuario FOREIGN KEY (realizado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE historial_estado_matricula IS 'Trazabilidad de cambios de estado de una matricula.';
COMMENT ON COLUMN historial_estado_matricula.historial_estado_matricula_id IS 'Identificador del cambio.';
COMMENT ON COLUMN historial_estado_matricula.matricula_id IS 'Matricula afectada.';
COMMENT ON COLUMN historial_estado_matricula.estado_anterior IS 'Estado previo, ausente al crear.';
COMMENT ON COLUMN historial_estado_matricula.estado_nuevo IS 'Estado resultante.';
COMMENT ON COLUMN historial_estado_matricula.motivo IS 'Motivo del cambio.';
COMMENT ON COLUMN historial_estado_matricula.realizado_por_usuario_id IS 'Administrador responsable cuando aplica.';
COMMENT ON COLUMN historial_estado_matricula.realizado_en IS 'Fecha y hora del cambio.';

CREATE TABLE pago (
    pago_id bigint GENERATED BY DEFAULT AS IDENTITY,
    matricula_id bigint NOT NULL,
    numero_pedido varchar(60) NOT NULL,
    operacion_proveedor varchar(120),
    origen varchar(20) NOT NULL,
    medio varchar(30),
    estado varchar(20) NOT NULL,
    moneda char(3) NOT NULL DEFAULT 'PEN',
    precio_regular_aplicado numeric(10,2) NOT NULL,
    precio_promocional_aplicado numeric(10,2),
    importe numeric(10,2) NOT NULL,
    referencia_externa varchar(180),
    ultimos_digitos varchar(4),
    motivo text,
    constancia_numero varchar(80),
    resultado_en timestamptz,
    requiere_atencion boolean NOT NULL DEFAULT false,
    detalle_atencion text,
    atendido_en timestamptz,
    atendido_por_usuario_id bigint,
    registrado_por_usuario_id bigint,
    iniciado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pago PRIMARY KEY (pago_id),
    CONSTRAINT uq_pago_numero_pedido UNIQUE (numero_pedido),
    CONSTRAINT uq_pago_operacion_proveedor UNIQUE (operacion_proveedor),
    CONSTRAINT uq_pago_constancia UNIQUE (constancia_numero),
    CONSTRAINT fk_pago_matricula FOREIGN KEY (matricula_id) REFERENCES matricula(matricula_id),
    CONSTRAINT fk_pago_atendido_por FOREIGN KEY (atendido_por_usuario_id) REFERENCES usuario(usuario_id),
    CONSTRAINT fk_pago_registrado_por FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuario(usuario_id)
);
COMMENT ON TABLE pago IS 'Cada intento o registro de pago asociado a una matricula.';
COMMENT ON COLUMN pago.pago_id IS 'Identificador del pago.';
COMMENT ON COLUMN pago.matricula_id IS 'Matricula vinculada.';
COMMENT ON COLUMN pago.numero_pedido IS 'Numero interno unico del intento.';
COMMENT ON COLUMN pago.operacion_proveedor IS 'Identificador unico retornado por la pasarela.';
COMMENT ON COLUMN pago.origen IS 'Origen EN_LINEA, MANUAL o EXONERADO.';
COMMENT ON COLUMN pago.medio IS 'Medio informado por la pasarela o administrador.';
COMMENT ON COLUMN pago.estado IS 'Estado REGISTRADO_MANUAL o EXONERADO en EP02; HU-047 agrega INICIADO, APROBADO, RECHAZADO, ERROR y ANULADO.';
COMMENT ON COLUMN pago.moneda IS 'Moneda confirmada para el intento.';
COMMENT ON COLUMN pago.precio_regular_aplicado IS 'Copia del precio regular al iniciar el intento.';
COMMENT ON COLUMN pago.precio_promocional_aplicado IS 'Copia del precio promocional vigente, si existia.';
COMMENT ON COLUMN pago.importe IS 'Importe final del intento.';
COMMENT ON COLUMN pago.referencia_externa IS 'Referencia adicional del banco, pasarela o comprobante.';
COMMENT ON COLUMN pago.ultimos_digitos IS 'Ultimos cuatro digitos si el proveedor los informa.';
COMMENT ON COLUMN pago.motivo IS 'Detalle del rechazo, error o ajuste.';
COMMENT ON COLUMN pago.constancia_numero IS 'Numero de constancia para pagos aprobados o exonerados.';
COMMENT ON COLUMN pago.resultado_en IS 'Momento del resultado definitivo.';
COMMENT ON COLUMN pago.requiere_atencion IS 'Indica si la escuela debe revisar una incidencia.';
COMMENT ON COLUMN pago.detalle_atencion IS 'Descripcion de la incidencia.';
COMMENT ON COLUMN pago.atendido_en IS 'Momento de atencion de la incidencia.';
COMMENT ON COLUMN pago.atendido_por_usuario_id IS 'Administrador que atendio la incidencia.';
COMMENT ON COLUMN pago.registrado_por_usuario_id IS 'Administrador que registro pago manual o exoneracion.';
COMMENT ON COLUMN pago.iniciado_en IS 'Momento de inicio del intento.';
COMMENT ON COLUMN pago.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN pago.modificado_en IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE notificacion (
    notificacion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id bigint NOT NULL,
    matricula_id bigint,
    pago_id bigint,
    tipo varchar(40) NOT NULL,
    destinatario varchar(254) NOT NULL,
    asunto varchar(220) NOT NULL,
    estado_envio varchar(15) NOT NULL DEFAULT 'PENDIENTE',
    intentos_envio integer NOT NULL DEFAULT 0,
    ultimo_error text,
    enviado_en timestamptz,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notificacion PRIMARY KEY (notificacion_id),
    CONSTRAINT fk_notificacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id),
    CONSTRAINT fk_notificacion_matricula FOREIGN KEY (matricula_id) REFERENCES matricula(matricula_id),
    CONSTRAINT fk_notificacion_pago FOREIGN KEY (pago_id) REFERENCES pago(pago_id)
);
COMMENT ON TABLE notificacion IS 'Registro simple de correos solicitados y su resultado de envio.';
COMMENT ON COLUMN notificacion.notificacion_id IS 'Identificador de la notificacion.';
COMMENT ON COLUMN notificacion.usuario_id IS 'Destinatario dentro del sistema.';
COMMENT ON COLUMN notificacion.matricula_id IS 'Matricula relacionada cuando aplica.';
COMMENT ON COLUMN notificacion.pago_id IS 'Pago relacionado cuando aplica.';
COMMENT ON COLUMN notificacion.tipo IS 'Evento que origino el correo.';
COMMENT ON COLUMN notificacion.destinatario IS 'Correo usado para el envio.';
COMMENT ON COLUMN notificacion.asunto IS 'Asunto enviado.';
COMMENT ON COLUMN notificacion.estado_envio IS 'Estado PENDIENTE, ENVIADO o ERROR.';
COMMENT ON COLUMN notificacion.intentos_envio IS 'Cantidad de intentos realizados.';
COMMENT ON COLUMN notificacion.ultimo_error IS 'Ultimo error tecnico informado.';
COMMENT ON COLUMN notificacion.enviado_en IS 'Fecha y hora de envio aceptado.';
COMMENT ON COLUMN notificacion.creado_en IS 'Fecha y hora de creacion.';
COMMENT ON COLUMN notificacion.modificado_en IS 'Fecha y hora de ultima modificacion.';

COMMIT;
